api_query = {
    "category_type_cb": {"0": "vse", "1": "prodej", "2": "pronajem", "3": "drazby"},
    "category_type_cb_detail": {
        "0": "vse",
        "1": "prodej",
        "2": "pronajem",
        "3": "drazby",
    },
    "category_main_cb": {
        "0": "vse",
        "1": "byty",
        "2": "domy",
        "3": "pozemky",
        "4": "komercni",
        "5": "ostatni",
    },
    "category_main_cb_detail": {
        "0": "vse",
        "1": "byt",
        "2": "dum",
        "3": "pozemek",
        "4": "komercni",
        "5": "ostatni",
    },
    "category_main_cb_project": {
        "1": "byty",
        "2": "domy",
        "3": "pozemky",
        "4": "komercni-nemovitosti",
        "5": "ostatni-reality",
    },
    "category_sub_cb": {
        "2": "1+kk",
        "3": "1+1",
        "4": "2+kk",
        "5": "2+1",
        "6": "3+kk",
        "7": "3+1",
        "8": "4+kk",
        "9": "4+1",
        "10": "5+kk",
        "11": "5+1",
        "12": "6-a-vice",
        "16": "atypicky",
        "18": "komercni-pozemky",
        "19": "stavebni-parcely",
        "20": "pole",
        "21": "lesy",
        "22": "louky",
        "23": "zahrady",
        "24": "ostatni-pozemky",
        "25": "kancelare",
        "26": "sklady",
        "27": "vyrobni-prostory",
        "28": "obchodni-prostory",
        "29": "ubytovani",
        "30": "restaurace",
        "31": "zemedelske-objekty",
        "32": "ostatni-komercni-prostory",
        "33": "chaty",
        "34": "garaze",
        "35": "pamatky-jine",
        "36": "jine-nemovitosti",
        "37": "rodinne-domy",
        "38": "cinzovni-domy",
        "39": "vily",
        "40": "projekty-na-klic",
        "43": "chalupy",
        "44": "zemedelske-usedlosti",
        "46": "rybniky",
        "47": "pokoj",
        "48": "sady-vinice",
        "49": "virtualni-kancelare",
        "50": "vinne-sklepy",
        "51": "pudni-prostory",
        "52": "garazova-stani",
        "53": "mobilheimy",
    },
    "category_sub_cb_detail": {
        "2": "1+kk",
        "3": "1+1",
        "4": "2+kk",
        "5": "2+1",
        "6": "3+kk",
        "7": "3+1",
        "8": "4+kk",
        "9": "4+1",
        "10": "5+kk",
        "11": "5+1",
        "12": "6-a-vice",
        "16": "atypicky",
        "18": "komercni",
        "19": "bydleni",
        "20": "pole",
        "21": "les",
        "22": "louka",
        "23": "zahrada",
        "24": "ostatni-pozemky",
        "25": "kancelare",
        "26": "sklad",
        "27": "vyrobni-prostor",
        "28": "obchodni-prostor",
        "29": "ubytovani",
        "30": "restaurace",
        "31": "zemedelsky",
        "32": "ostatni-komercni-prostory",
        "33": "chata",
        "34": "garaz",
        "35": "pamatka",
        "36": "jine-nemovitosti",
        "37": "rodinny",
        "38": "cinzovni-dum",
        "39": "vila",
        "40": "na-klic",
        "43": "chalupa",
        "44": "zemedelska-usedlost",
        "46": "rybnik",
        "47": "pokoj",
        "48": "sady-vinice",
        "49": "virtualni-kancelar",
        "50": "vinny-sklep",
        "51": "pudni-prostor",
        "52": "garazove-stani",
        "53": "mobilni-domek",
    },
    "locality_region_id": {
        "1": "jihocesky-kraj",
        "2": "plzensky-kraj",
        "3": "karlovarsky-kraj",
        "4": "ustecky-kraj",
        "5": "liberecky-kraj",
        "6": "kralovehradecky-kraj",
        "7": "pardubicky-kraj",
        "8": "olomoucky-kraj",
        "9": "zlinsky-kraj",
        "10": "praha",
        "11": "stredocesky-kraj",
        "12": "moravskoslezsky-kraj",
        "13": "vysocina-kraj",
        "14": "jihomoravsky-kraj",
    },
    "locality_district_id": {
        "1": "ceske-budejovice",
        "2": "cesky-krumlov",
        "3": "jindrichuv-hradec",
        "4": "pisek",
        "5": "prachatice",
        "6": "strakonice",
        "7": "tabor",
        "8": "domazlice",
        "9": "cheb",
        "10": "karlovy-vary",
        "11": "klatovy",
        "12": "plzen",
        "13": "plzen-jih",
        "14": "plzen-sever",
        "15": "rokycany",
        "16": "sokolov",
        "17": "tachov",
        "18": "ceska-lipa",
        "19": "decin",
        "20": "chomutov",
        "21": "jablonec-nad-nisou",
        "22": "liberec",
        "23": "litomerice",
        "24": "louny",
        "25": "most",
        "26": "teplice",
        "27": "usti-nad-labem",
        "28": "hradec-kralove",
        "29": "chrudim",
        "30": "jicin",
        "31": "nachod",
        "32": "pardubice",
        "33": "rychnov-nad-kneznou",
        "34": "semily",
        "35": "svitavy",
        "36": "trutnov",
        "37": "usti-nad-orlici",
        "38": "zlin",
        "39": "kromeriz",
        "40": "prostejov",
        "41": "uherske-hradiste",
        "42": "olomouc",
        "43": "prerov",
        "44": "sumperk",
        "45": "vsetin",
        "46": "jesenik",
        "48": "benesov",
        "49": "beroun",
        "50": "kladno",
        "51": "kolin",
        "52": "kutna-hora",
        "53": "mlada-boleslav",
        "54": "melnik",
        "55": "nymburk",
        "56": "praha-vychod",
        "57": "praha-zapad",
        "58": "pribram",
        "59": "rakovnik",
        "60": "bruntal",
        "61": "frydek-mistek",
        "62": "karvina",
        "63": "novy-jicin",
        "64": "opava",
        "65": "ostrava",
        "66": "havlickuv-brod",
        "67": "jihlava",
        "68": "pelhrimov",
        "69": "trebic",
        "70": "zdar-nad-sazavou",
        "71": "blansko",
        "72": "brno",
        "73": "brno-venkov",
        "74": "breclav",
        "75": "hodonin",
        "76": "vyskov",
        "77": "znojmo",
        "5001": "praha-1",
        "5002": "praha-2",
        "5003": "praha-3",
        "5004": "praha-4",
        "5005": "praha-5",
        "5006": "praha-6",
        "5007": "praha-7",
        "5008": "praha-8",
        "5009": "praha-9",
        "5010": "praha-10",
    },
    "locality_country_id": {
        "8": "albanie",
        "12": "alzirsko",
        "20": "andora",
        "40": "rakousko",
        "56": "belgie",
        "70": "bosna-a-hercegovina",
        "76": "brazilie",
        "96": "brunej",
        "100": "bulharsko",
        "112": "ceska-republika",
        "132": "kapverdy",
        "188": "kostarika",
        "191": "chorvatsko",
        "196": "kypr",
        "208": "dansko",
        "214": "dominikanska-republika",
        "233": "estonsko",
        "234": "faerske-ostrovy",
        "246": "finsko",
        "250": "francie",
        "268": "gruzie",
        "276": "nemecko",
        "292": "gibraltar",
        "300": "recko",
        "336": "vatikan",
        "348": "madarsko",
        "352": "island",
        "372": "irsko",
        "376": "izrael",
        "380": "italie",
        "400": "jordansko",
        "422": "libanon",
        "428": "lotyssko",
        "434": "libye",
        "438": "lichtenstejnsko",
        "440": "litva",
        "442": "lucembursko",
        "470": "malta",
        "484": "mexiko",
        "492": "monako",
        "498": "moldavsko",
        "499": "cerna-hora",
        "504": "maroko",
        "528": "nizozemi",
        "578": "norsko",
        "616": "polsko",
        "620": "portugalsko",
        "642": "rumunsko",
        "643": "rusko",
        "674": "san-marino",
        "682": "saudska-arabie",
        "688": "srbsko",
        "703": "slovenska-republika",
        "705": "slovinsko",
        "724": "spanelsko",
        "752": "svedsko",
        "756": "svycarsko",
        "760": "syrie",
        "784": "spojene-arabske-emiraty",
        "788": "tunisko",
        "792": "turecko",
        "804": "ukrajina",
        "807": "makedonie",
        "818": "egypt",
        "826": "velka-britanie",
        "831": "guernsey",
        "832": "jersey",
        "834": "thajsko",
        "840": "spojene-staty-americke",
        "10000": "zahranici",
        "10001": "vsechny-staty",
    },
    "building_type_search": {"1": "panelova", "2": "cihlova", "3": "ostatni"},
    "ownership": {"1": "osobni", "2": "druzstevni", "3": "statni-obecni"},
    "building_condition": {
        "1": "velmi-dobry-stav",
        "2": "dobry-stav",
        "3": "spatny-stav",
        "4": "ve-vystavbe",
        "5": "developerske-projekty",
        "6": "novostavby",
        "7": "k-demolici",
        "8": "pred-rekonstrukci",
        "9": "po-rekonstrukci",
    },
    "room_count_cb": {
        "1": "1-pokoj",
        "2": "2-pokoje",
        "3": "3-pokoje",
        "4": "4-pokoje",
        "5": "5-a-vice",
        "6": "atypicky",
    },
    "furnished": {"1": "vybaveny", "2": "nevybaveny", "3": "castecne"},
    "something_more1": {
        "3090": "balkon",
        "3100": "lodzie",
        "3110": "terasa",
        "3120": "sklep",
    },
    "something_more2": {"3130": "bazen", "3140": "parkovani", "3150": "garaz"},
    "something_more3": {"1820": "bezbarierovy", "3310": "vytah"},
    "something_more4": {"2123": "nizkoenergeticky", "100111": "drevostavba"},
    "object_type": {"1": "prizemni", "2": "patrovy"},
    "object_kind_search": {"1": "samostatny", "2": "radovy"},
    "sort": {"0": "nejnovejsi", "1": "nejlevnejsi", "2": "nejdrazsi", "4": "nejblizsi"},
    "tab": {
        "info": "",
        "advert": "inzeraty",
        "seller": "makleri",
        "premise": "pobocky",
    },
    "estate_age": {"2": "dnes", "8": "tyden", "31": "mesic"},
}


city_to_region = {
    "1": {"name": "České Budějovice", "locality_region_id": "1"},
    "2": {"name": "Český Krumlov", "locality_region_id": "1"},
    "3": {"name": "Jindřichův Hradec", "locality_region_id": "1"},
    "4": {"name": "Písek", "locality_region_id": "1"},
    "5": {"name": "Prachatice", "locality_region_id": "1"},
    "6": {"name": "Strakonice", "locality_region_id": "1"},
    "7": {"name": "Tábor", "locality_region_id": "1"},
    "71": {"name": "Blansko", "locality_region_id": "14"},
    "74": {"name": "Břeclav", "locality_region_id": "14"},
    "72": {"name": "Brno-město", "locality_region_id": "14"},
    "73": {"name": "Brno-venkov", "locality_region_id": "14"},
    "75": {"name": "Hodonín", "locality_region_id": "14"},
    "76": {"name": "Vyškov", "locality_region_id": "14"},
    "77": {"name": "Znojmo", "locality_region_id": "14"},
    "9": {"name": "Cheb", "locality_region_id": "3"},
    "10": {"name": "Karlovy Vary", "locality_region_id": "3"},
    "16": {"name": "Sokolov", "locality_region_id": "3"},
    "28": {"name": "Hradec Králové", "locality_region_id": "6"},
    "30": {"name": "Jičín", "locality_region_id": "6"},
    "31": {"name": "Náchod", "locality_region_id": "6"},
    "33": {"name": "Rychnov nad Kněžnou", "locality_region_id": "6"},
    "36": {"name": "Trutnov", "locality_region_id": "6"},
    "18": {"name": "Česká Lípa", "locality_region_id": "5"},
    "21": {"name": "Jablonec nad Nisou", "locality_region_id": "5"},
    "22": {"name": "Liberec", "locality_region_id": "5"},
    "34": {"name": "Semily", "locality_region_id": "5"},
    "60": {"name": "Bruntál", "locality_region_id": "12"},
    "61": {"name": "Frýdek-Místek", "locality_region_id": "12"},
    "62": {"name": "Karviná", "locality_region_id": "12"},
    "63": {"name": "Nový Jičín", "locality_region_id": "12"},
    "64": {"name": "Opava", "locality_region_id": "12"},
    "65": {"name": "Ostrava-město", "locality_region_id": "12"},
    "46": {"name": "Jeseník", "locality_region_id": "8"},
    "42": {"name": "Olomouc", "locality_region_id": "8"},
    "43": {"name": "Přerov", "locality_region_id": "8"},
    "40": {"name": "Prostějov", "locality_region_id": "8"},
    "44": {"name": "Šumperk", "locality_region_id": "8"},
    "29": {"name": "Chrudim", "locality_region_id": "7"},
    "32": {"name": "Pardubice", "locality_region_id": "7"},
    "35": {"name": "Svitavy", "locality_region_id": "7"},
    "37": {"name": "Ústí nad Orlicí", "locality_region_id": "7"},
    "8": {"name": "Domažlice", "locality_region_id": "2"},
    "11": {"name": "Klatovy", "locality_region_id": "2"},
    "13": {"name": "Plzeň-jih", "locality_region_id": "2"},
    "12": {"name": "Plzeň-město", "locality_region_id": "2"},
    "14": {"name": "Plzeň-sever", "locality_region_id": "2"},
    "15": {"name": "Rokycany", "locality_region_id": "2"},
    "17": {"name": "Tachov", "locality_region_id": "2"},
    "5001": {"name": "Praha 1", "locality_region_id": "10"},
    "5002": {"name": "Praha 2", "locality_region_id": "10"},
    "5003": {"name": "Praha 3", "locality_region_id": "10"},
    "5004": {"name": "Praha 4", "locality_region_id": "10"},
    "5005": {"name": "Praha 5", "locality_region_id": "10"},
    "5006": {"name": "Praha 6", "locality_region_id": "10"},
    "5007": {"name": "Praha 7", "locality_region_id": "10"},
    "5008": {"name": "Praha 8", "locality_region_id": "10"},
    "5009": {"name": "Praha 9", "locality_region_id": "10"},
    "5010": {"name": "Praha 10", "locality_region_id": "10"},
    "48": {"name": "Benešov", "locality_region_id": "11"},
    "49": {"name": "Beroun", "locality_region_id": "11"},
    "50": {"name": "Kladno", "locality_region_id": "11"},
    "51": {"name": "Kolín", "locality_region_id": "11"},
    "52": {"name": "Kutná Hora", "locality_region_id": "11"},
    "54": {"name": "Mělník", "locality_region_id": "11"},
    "53": {"name": "Mladá Boleslav", "locality_region_id": "11"},
    "55": {"name": "Nymburk", "locality_region_id": "11"},
    "56": {"name": "Praha-východ", "locality_region_id": "11"},
    "57": {"name": "Praha-západ", "locality_region_id": "11"},
    "58": {"name": "Příbram", "locality_region_id": "11"},
    "59": {"name": "Rakovník", "locality_region_id": "11"},
    "20": {"name": "Chomutov", "locality_region_id": "4"},
    "19": {"name": "Děčín", "locality_region_id": "4"},
    "23": {"name": "Litoměřice", "locality_region_id": "4"},
    "24": {"name": "Louny", "locality_region_id": "4"},
    "25": {"name": "Most", "locality_region_id": "4"},
    "26": {"name": "Teplice", "locality_region_id": "4"},
    "27": {"name": "Ústí nad Labem", "locality_region_id": "4"},
    "66": {"name": "Havlíčkův Brod", "locality_region_id": "13"},
    "67": {"name": "Jihlava", "locality_region_id": "13"},
    "68": {"name": "Pelhřimov", "locality_region_id": "13"},
    "69": {"name": "Třebíč", "locality_region_id": "13"},
    "70": {"name": "Žďár nad Sázavou", "locality_region_id": "13"},
    "39": {"name": "Kroměříž", "locality_region_id": "9"},
    "41": {"name": "Uherské Hradiště", "locality_region_id": "9"},
    "45": {"name": "Vsetín", "locality_region_id": "9"},
    "38": {"name": "Zlín", "locality_region_id": "9"},
}

city_to_region = {
    "1": "1",
    "2": "1",
    "3": "1",
    "4": "1",
    "5": "1",
    "6": "1",
    "7": "1",
    "71": "14",
    "74": "14",
    "72": "14",
    "73": "14",
    "75": "14",
    "76": "14",
    "77": "14",
    "9": "3",
    "10": "3",
    "16": "3",
    "28": "6",
    "30": "6",
    "31": "6",
    "33": "6",
    "36": "6",
    "18": "5",
    "21": "5",
    "22": "5",
    "34": "5",
    "60": "12",
    "61": "12",
    "62": "12",
    "63": "12",
    "64": "12",
    "65": "12",
    "46": "8",
    "42": "8",
    "43": "8",
    "40": "8",
    "44": "8",
    "29": "7",
    "32": "7",
    "35": "7",
    "37": "7",
    "8": "2",
    "11": "2",
    "13": "2",
    "12": "2",
    "14": "2",
    "15": "2",
    "17": "2",
    "5001": "10",
    "5002": "10",
    "5003": "10",
    "5004": "10",
    "5005": "10",
    "5006": "10",
    "5007": "10",
    "5008": "10",
    "5009": "10",
    "5010": "10",
    "48": "11",
    "49": "11",
    "50": "11",
    "51": "11",
    "52": "11",
    "54": "11",
    "53": "11",
    "55": "11",
    "56": "11",
    "57": "11",
    "58": "11",
    "59": "11",
    "20": "4",
    "19": "4",
    "23": "4",
    "24": "4",
    "25": "4",
    "26": "4",
    "27": "4",
    "66": "13",
    "67": "13",
    "68": "13",
    "69": "13",
    "70": "13",
    "39": "9",
    "41": "9",
    "45": "9",
    "38": "9",
}
